export interface FAQItem {
  id: string;
  question: string;
  answer: string;
  tags: string[];
}

export const faqData: FAQItem[] = [
  {
    id: 'what-does-corqon-do',
    question: 'What does Corqon actually do?',
    answer: 'Corqon connects operational data streams and detects systemic performance loss early. It surfaces patterns behind instability, rework, fragmentation, and hidden margin erosion. The output is a weekly brief plus leadership actions teams can execute.',
    tags: ['performance', 'margins', 'productivity'],
  },
  {
    id: 'what-problem-does-corqon-solve',
    question: 'What problem does Corqon solve?',
    answer: 'Most organizations lose output through fragmentation, planning volatility, and invisible strain before it shows up as absence or churn. Corqon makes those signals visible early and ties them to clear interventions. That protects performance and margins.',
    tags: ['performance', 'margins', 'operations'],
  },
  {
    id: 'who-is-corqon-for',
    question: 'What kind of companies is Corqon built for?',
    answer: 'Corqon is built for mid-sized to large organizations that operate at scale and depend on predictable performance. It is especially relevant for companies where operational complexity directly impacts financial outcomes.',
    tags: ['companies', 'operations', 'finance', 'scaling'],
  },
  {
    id: 'who-is-corqon-for-org',
    question: 'Who is Corqon for?',
    answer: 'Corqon is built for leadership, HR, and operations in fast-growing companies. It helps teams reduce avoidable absence, protect focus, and prevent hidden capacity loss. It is decision support, not employee surveillance.',
    tags: ['leadership', 'hr', 'operations'],
  },
  {
    id: 'who-is-corqon-designed-for',
    question: 'Who is Corqon designed for inside an organization?',
    answer: 'Corqon is designed for leadership, finance, operations, and strategy teams. The platform is intentionally built so insights can be understood without technical or data science expertise.',
    tags: ['leadership', 'finance', 'operations'],
  },
  {
    id: 'is-corqon-wellness-platform',
    question: 'Is Corqon a wellness or wellbeing platform?',
    answer: 'Corqon is not a wellness platform and does not offer wellbeing programs, coaching, or health interventions. It focuses on organizational systems and performance risk, not individual wellbeing.',
    tags: ['operations'],
  },
  {
    id: 'how-is-corqon-different-from-wellbeing-app',
    question: 'How is Corqon different from a wellbeing app?',
    answer: 'Corqon is not a wellbeing app. It focuses on system-level patterns that reduce performance, like disruption, volatility, and rework. The goal is better operating conditions and measurable business outcomes.',
    tags: ['operations', 'product'],
  },
  {
    id: 'is-corqon-hr-tool',
    question: 'Is Corqon an HR tool?',
    answer: 'Corqon supports HR with insights, but it is not an HR management system. Its primary role is to support leadership and finance with system-level performance visibility.',
    tags: ['leadership', 'finance', 'operations'],
  },
  {
    id: 'does-corqon-monitor-employees',
    question: 'Does Corqon monitor or evaluate individual employees?',
    answer: 'Corqon never tracks, scores, or evaluates individuals. All analysis is performed at team or organizational level to avoid surveillance and misuse.',
    tags: ['privacy', 'governance'],
  },
  {
    id: 'do-you-track-individual-employees',
    question: 'Do you track individual employees?',
    answer: 'No. Corqon is designed for system-level insights and avoids individual scoring. The focus is on team and organizational patterns that leadership can act on.',
    tags: ['privacy', 'governance'],
  },
  {
    id: 'what-is-hidden-performance-loss',
    question: 'What does "hidden performance loss" mean?',
    answer: 'Hidden performance loss refers to productivity erosion caused by fragmentation, instability, overload, and insufficient recovery. These losses build gradually and rarely appear in traditional dashboards.',
    tags: ['performance', 'productivity'],
  },
  {
    id: 'why-is-performance-loss-hard-to-detect',
    question: 'Why is performance loss hard to detect with existing tools?',
    answer: 'Most BI and reporting tools focus on outcomes after they occur, such as financial results or absenteeism. Corqon focuses on upstream signals that appear before those outcomes become visible.',
    tags: ['performance', 'reporting'],
  },
  {
    id: 'data-sources',
    question: 'What data sources does Corqon use?',
    answer: 'Corqon connects to existing systems such as HR platforms, scheduling tools, planning software, and operational data sources. It is designed to work with the systems companies already use.',
    tags: ['integrations', 'data'],
  },
  {
    id: 'does-corqon-require-wearables',
    question: 'Does Corqon require wearables or health data?',
    answer: 'Corqon does not depend on wearables, medical data, or personal health metrics. Its insights are primarily derived from organizational and operational data.',
    tags: ['data', 'privacy'],
  },
  {
    id: 'does-corqon-require-surveys',
    question: 'Does Corqon require employee input or surveys?',
    answer: 'Employees are not required to fill in surveys, log activities, or manually enter data. Corqon works passively using existing systems.',
    tags: ['data', 'operations'],
  },
  {
    id: 'can-corqon-work-with-imperfect-data',
    question: 'Can Corqon work with incomplete or imperfect data?',
    answer: 'Corqon is designed for real-world environments where data is often imperfect. It focuses on pattern consistency over time rather than perfect datasets.',
    tags: ['data'],
  },
  {
    id: 'bi-tools',
    question: 'Does Corqon replace BI or analytics tools?',
    answer: 'Corqon does not replace BI or reporting tools. It complements them by surfacing patterns those tools are not designed to detect.',
    tags: ['reporting'],
  },
  {
    id: 'insights',
    question: 'What kind of insights does Corqon deliver?',
    answer: 'Corqon highlights sustained overload, structural inefficiencies, instability, and accumulating performance risk. These insights are framed to support operational and financial decisions.',
    tags: ['insights', 'operations', 'finance'],
  },
  {
    id: 'are-insights-actionable',
    question: 'Are Corqon\'s insights actionable?',
    answer: 'Insights are designed to clearly show where attention is needed and where risk accumulates. Corqon does not prescribe actions but enables informed decision-making.',
    tags: ['insights', 'operations'],
  },
  {
    id: 'does-corqon-make-predictions',
    question: 'Does Corqon make predictions?',
    answer: 'Corqon provides early signals and risk accumulation trends rather than deterministic forecasts. Its value lies in early detection, not exact prediction.',
    tags: ['insights', 'operations'],
  },
  {
    id: 'ai',
    question: 'Does Corqon use artificial intelligence?',
    answer: 'Corqon uses advanced models to detect patterns and correlations across complex data streams. Strong emphasis is placed on explainability and consistency.',
    tags: ['ai'],
  },
  {
    id: 'is-corqon-black-box',
    question: 'Is Corqon a black-box system?',
    answer: 'Corqon avoids opaque scoring and unexplained outputs. Insights are grounded in observable patterns that can be discussed and validated.',
    tags: ['governance'],
  },
  {
    id: 'does-corqon-automate-decisions',
    question: 'Does Corqon automate decisions?',
    answer: 'Corqon informs decisions but never automates them. Responsibility always remains with leadership.',
    tags: ['leadership', 'governance'],
  },
  {
    id: 'can-corqon-be-used-in-executive-reporting',
    question: 'Can Corqon be used in executive or board reporting?',
    answer: 'Corqon is designed specifically for executive and board-level discussions. Insights are presented with clarity and financial relevance.',
    tags: ['leadership', 'finance', 'reporting'],
  },
  {
    id: 'how-does-corqon-relate-insights-to-financial-impact',
    question: 'How does Corqon relate insights to financial impact?',
    answer: 'Corqon translates system behavior into capacity loss and margin pressure. This allows finance teams to connect operational signals to financial outcomes.',
    tags: ['finance', 'operations'],
  },
  {
    id: 'onboarding',
    question: 'How long does onboarding take?',
    answer: 'Onboarding typically takes weeks rather than months. Implementation focuses on configuration rather than rebuilding systems.',
    tags: ['onboarding'],
  },
  {
    id: 'how-long-does-integration-take',
    question: 'How long does integration take?',
    answer: 'It depends on your sources and governance. Many teams start with a minimal setup to establish a baseline quickly. We can provide a short implementation timeline during onboarding.',
    tags: ['onboarding', 'integrations', 'implementation'],
  },
  {
    id: 'how-much-it-involvement',
    question: 'How much IT involvement is required?',
    answer: 'IT involvement is usually limited to integration and security alignment. No large-scale system changes are required.',
    tags: ['onboarding', 'integrations'],
  },
  {
    id: 'can-corqon-be-rolled-out-gradually',
    question: 'Can Corqon be rolled out gradually?',
    answer: 'Corqon can be deployed in phases across teams, departments, or regions. This allows organizations to scale adoption at their own pace.',
    tags: ['onboarding', 'scaling'],
  },
  {
    id: 'privacy',
    question: 'How does Corqon handle privacy?',
    answer: 'Corqon is designed with privacy by default, using aggregation and anonymization wherever possible. Access is controlled through strict role-based permissions.',
    tags: ['privacy', 'security'],
  },
  {
    id: 'gdpr',
    question: 'Is Corqon GDPR compliant?',
    answer: 'Corqon is built to operate within GDPR principles such as data minimization and purpose limitation. Final compliance depends on customer-specific configurations.',
    tags: ['gdpr', 'compliance'],
  },
  {
    id: 'how-do-you-handle-gdpr',
    question: 'How do you handle GDPR?',
    answer: 'We support GDPR-aligned implementation through data minimization, clear purpose, and documented controls. We can provide a privacy policy and DPA for review. Exact obligations depend on your role as controller and our role as processor.',
    tags: ['gdpr', 'compliance', 'privacy'],
  },
  {
    id: 'who-owns-data',
    question: 'Who owns the data processed by Corqon?',
    answer: 'The customer always retains ownership of their data. Corqon processes data solely for the agreed analytical purposes.',
    tags: ['privacy', 'governance'],
  },
  {
    id: 'where-is-data-stored',
    question: 'Where is data stored?',
    answer: 'Data storage depends on customer requirements, regional regulations, and security policies. Deployment options are aligned accordingly.',
    tags: ['privacy', 'security', 'compliance'],
  },
  {
    id: 'is-corqon-suitable-for-regulated-industries',
    question: 'Is Corqon suitable for regulated industries?',
    answer: 'Corqon is designed for environments with strict governance, compliance, and audit requirements. It is suitable for highly regulated sectors.',
    tags: ['compliance', 'governance', 'audits'],
  },
  {
    id: 'is-corqon-suitable-for-international-organizations',
    question: 'Is Corqon suitable for international organizations?',
    answer: 'Corqon supports multiple regions, legal entities, and organizational structures. It is built to operate at international scale.',
    tags: ['scaling', 'operations'],
  },
  {
    id: 'how-does-corqon-scale',
    question: 'How does Corqon scale as organizations grow?',
    answer: 'Corqon scales across teams and departments without requiring structural redesign. The system adapts as organizational complexity increases.',
    tags: ['scaling'],
  },
  {
    id: 'how-is-success-measured',
    question: 'How is success measured with Corqon?',
    answer: 'Success is measured through improved visibility, earlier intervention, and reduced accumulation of performance-related risk.',
    tags: ['operations'],
  },
  {
    id: 'does-corqon-replace-consultants',
    question: 'Does Corqon replace consultants or advisors?',
    answer: 'Corqon complements advisory work by providing continuous system-level visibility. It does not replace strategic or human judgment.',
    tags: ['operations'],
  },
  {
    id: 'how-does-corqon-differ-from-engagement-surveys',
    question: 'How does Corqon differ from engagement surveys?',
    answer: 'Engagement surveys capture sentiment at a moment in time. Corqon analyzes ongoing system behavior and structural patterns.',
    tags: ['operations', 'surveys'],
  },
  {
    id: 'how-is-corqon-different-from-survey-tool',
    question: 'How is Corqon different from a survey tool?',
    answer: 'Surveys capture perception at a moment in time. Corqon adds a system signal layer that detects structural patterns continuously and turns them into weekly leadership actions. If surveys exist, Corqon can use them as one input, not the whole story.',
    tags: ['operations', 'surveys', 'product'],
  },
  {
    id: 'does-corqon-diagnose-burnout',
    question: 'Does Corqon diagnose burnout or health issues?',
    answer: 'Corqon does not diagnose individuals or conditions. It identifies system-level risk factors that precede visible problems.',
    tags: ['operations'],
  },
  {
    id: 'how-does-corqon-handle-organizational-change',
    question: 'How does Corqon handle organizational change?',
    answer: 'Corqon adapts dynamically to restructuring, growth, or mergers by recalibrating patterns over time.',
    tags: ['operations', 'scaling'],
  },
  {
    id: 'what-happens-if-no-action-taken',
    question: 'What happens if Corqon signals risk but no action is taken?',
    answer: 'Corqon continues to surface the accumulating impact. Inaction becomes visible rather than hidden.',
    tags: ['operations'],
  },
  {
    id: 'can-corqon-create-perverse-incentives',
    question: 'Can Corqon create perverse incentives?',
    answer: 'Corqon intentionally avoids individual metrics and rankings. This reduces the risk of misuse or unintended incentives.',
    tags: ['governance'],
  },
  {
    id: 'is-corqon-reactive-or-proactive',
    question: 'Is Corqon reactive or proactive?',
    answer: 'Corqon is proactive by design. It focuses on early signals rather than late-stage outcomes.',
    tags: ['operations'],
  },
  {
    id: 'can-corqon-support-capacity-planning',
    question: 'Can Corqon support capacity planning?',
    answer: 'By identifying sustained overload and instability, Corqon supports better capacity and planning decisions.',
    tags: ['operations'],
  },
  {
    id: 'is-corqon-suitable-for-remote-work',
    question: 'Is Corqon suitable for remote or hybrid work?',
    answer: 'Fragmentation and instability are especially relevant in remote and hybrid environments. Corqon is well-suited to these models.',
    tags: ['operations'],
  },
  {
    id: 'can-corqon-be-audited',
    question: 'Can Corqon be audited?',
    answer: 'Corqon\'s data processing and logic can be reviewed and audited. Transparency is a core design principle.',
    tags: ['audits', 'governance', 'compliance'],
  },
  {
    id: 'does-corqon-require-employee-consent',
    question: 'Does Corqon require employee consent?',
    answer: 'Consent requirements depend on local regulations and the data sources used. Corqon is designed to minimize personal data exposure.',
    tags: ['privacy', 'compliance'],
  },
  {
    id: 'what-problem-does-corqon-ultimately-solve',
    question: 'What problem does Corqon ultimately solve?',
    answer: 'Corqon reduces decision blindness by making invisible performance loss visible before it compounds into margin damage.',
    tags: ['performance', 'margins'],
  },
  {
    id: 'who-are-founders',
    question: 'Who are the founders of Corqon?',
    answer: 'Corqon was founded by Kaya Güneş and Dennis de Kort. Together, they combine strategic, technical, and operational expertise with a shared focus on building data-driven systems that help organizations protect performance and margins at scale.',
    tags: ['leadership'],
  },
  {
    id: 'pricing',
    question: 'How is Corqon priced?',
    answer: 'Corqon follows a B2B pricing model based on organization size and scope of data integration. Exact pricing is discussed during onboarding to ensure alignment with company structure and needs.',
    tags: ['pricing', 'cost', 'contract', 'b2b', 'enterprise'],
  },
  {
    id: 'how-does-pricing-work',
    question: 'How does pricing work?',
    answer: 'Pricing depends on scope, team count, and integration needs. We usually structure it to match enterprise usage and rollout stages. The fastest way is to review a pilot scope and propose a plan.',
    tags: ['pricing', 'cost', 'contract', 'b2b', 'enterprise'],
  },
  {
    id: 'customization',
    question: 'Can Corqon be customized per organization?',
    answer: 'Yes. Corqon adapts to organizational structure, roles, and data availability. The system is configurable without requiring custom development.',
    tags: ['customization', 'configuration', 'organization', 'roles', 'data'],
  },
  {
    id: 'what-outcomes-can-we-expect',
    question: 'What outcomes can we expect?',
    answer: 'Corqon helps reduce hidden productivity loss, avoid rework, and intervene earlier before absence becomes expensive. Results depend on your baseline and the actions you implement. We focus on measurable signals and clear intervention tracking.',
    tags: ['outcomes', 'performance', 'operations'],
  },
  {
    id: 'what-does-weekly-briefing-include',
    question: 'What does the weekly briefing include?',
    answer: 'A concise summary of what changed, why it matters, and what to do next. You typically get key signals, risk areas, and a Monday plan with owners and effort level. It is designed for leadership execution, not dashboard browsing.',
    tags: ['briefing', 'reporting', 'leadership'],
  },
  {
    id: 'what-is-monday-plan',
    question: 'What is the Monday plan?',
    answer: 'The Monday plan is a short set of prioritized actions for leadership and HR. Each action includes an owner, expected effort, and intended outcome. It helps teams move from insight to execution.',
    tags: ['briefing', 'reporting', 'leadership', 'actions'],
  },
  {
    id: 'do-you-replace-managers-or-hr',
    question: 'Do you replace managers or HR?',
    answer: 'No. Corqon supports managers and HR with clearer signals and action options. Decisions remain with leadership.',
    tags: ['leadership', 'hr', 'operations'],
  },
  {
    id: 'is-corqon-medical-product',
    question: 'Is Corqon a medical product?',
    answer: 'No. Corqon is not a medical or diagnostic tool. It provides organizational decision support based on system-level patterns.',
    tags: ['product', 'operations'],
  },
  {
    id: 'can-employees-be-identified',
    question: 'Can employees be identified in Corqon?',
    answer: 'The intent is to prevent individual identification and keep signals at team level. The exact configuration depends on data sources and aggregation thresholds. We can walk you through the privacy setup during procurement.',
    tags: ['privacy', 'governance'],
  },
  {
    id: 'do-you-score-employees',
    question: 'Do you score employees?',
    answer: 'No. Corqon avoids employee-level scoring. The output is operational signals and leadership actions at team or org level.',
    tags: ['privacy', 'governance'],
  },
  {
    id: 'do-you-have-dpa',
    question: 'Do you have a DPA?',
    answer: 'We can provide a Data Processing Agreement for procurement review. It documents responsibilities, processing purposes, and core controls.',
    tags: ['privacy', 'compliance', 'procurement'],
  },
  {
    id: 'what-data-do-you-store',
    question: 'What data do you store?',
    answer: 'Corqon stores what is required to generate system-level insights and track changes over time. The exact data depends on your connected sources and configuration. Data minimization is the default principle.',
    tags: ['privacy', 'data', 'security'],
  },
  {
    id: 'how-long-do-you-retain-data',
    question: 'How long do you retain data?',
    answer: 'Retention depends on your policy and the signals you want to track. We can align retention and deletion rules during implementation and document them.',
    tags: ['privacy', 'data', 'compliance'],
  },
  {
    id: 'who-can-access-corqon-data',
    question: 'Who can access Corqon data?',
    answer: 'Access is role-based and designed for leadership and authorized stakeholders. We can align access rules with your governance model. Access expectations should be confirmed during rollout.',
    tags: ['privacy', 'security', 'governance'],
  },
  {
    id: 'can-we-run-corqon-without-hr-data',
    question: 'Can we run Corqon without HR data?',
    answer: 'Often yes. Corqon can work with operational signals and still detect instability and fragmentation patterns. HR data can be optional and used as a validation layer if you choose.',
    tags: ['data', 'integrations', 'hr'],
  },
  {
    id: 'how-do-we-communicate-to-employees',
    question: 'How do we communicate this to employees?',
    answer: 'Keep it simple: Corqon is about improving operating conditions, not monitoring individuals. Explain the team-level approach and what decisions it supports. Make privacy safeguards explicit.',
    tags: ['adoption', 'privacy', 'communication'],
  },
  {
    id: 'do-you-have-security-documentation',
    question: 'Do you have security documentation?',
    answer: 'We can provide a security overview for procurement. It covers access controls, retention, and handling practices at a high level. If you need specific requirements, we can review them together.',
    tags: ['security', 'procurement', 'compliance'],
  },
  {
    id: 'are-you-soc2-or-iso27001',
    question: 'Are you SOC 2 or ISO 27001 certified?',
    answer: 'If you require specific certifications, we can discuss them during procurement. If a certification is not in place yet, we can still provide a clear security overview and controls documentation. Procurement requirements vary by company.',
    tags: ['security', 'procurement', 'compliance', 'certifications'],
  },
  {
    id: 'do-you-support-sso',
    question: 'Do you support SSO?',
    answer: 'If SSO is required, we can discuss options during implementation. Support depends on your identity provider and rollout scope. Confirm requirements during procurement.',
    tags: ['security', 'integrations', 'procurement'],
  },
  {
    id: 'can-we-restrict-access-by-role',
    question: 'Can we restrict access by role?',
    answer: 'Yes, role-based access is a standard expectation for leadership tooling. We can align roles and permissions with your governance model. Final setup depends on your org structure.',
    tags: ['security', 'governance'],
  },
  {
    id: 'can-we-export-data',
    question: 'Can we export data?',
    answer: 'Export needs vary by customer. We can discuss the right export and reporting approach for your governance and analytics needs. The goal is to keep insights actionable and privacy-safe.',
    tags: ['data', 'governance', 'reporting'],
  },
  {
    id: 'what-data-sources-can-corqon-connect-to',
    question: 'What data sources can Corqon connect to?',
    answer: 'Corqon is designed to integrate with common operational and HR systems. Exact sources depend on your stack and what signals you want to measure. In a pilot we confirm feasibility and minimal required inputs.',
    tags: ['integrations', 'data'],
  },
  {
    id: 'do-we-need-to-change-our-tools',
    question: 'Do we need to change our tools?',
    answer: 'No. Corqon is meant to work with the tools you already use. We focus on connecting signals, not replacing systems.',
    tags: ['integrations', 'operations'],
  },
  {
    id: 'what-is-minimum-data-needed',
    question: 'What is the minimum data needed to start?',
    answer: 'Enough operational signal to detect disruption and fragmentation trends, plus clear team structure for aggregation. HR data can be optional. We confirm the minimum viable setup in a kickoff call.',
    tags: ['integrations', 'data', 'onboarding'],
  },
  {
    id: 'can-corqon-work-for-distributed-teams',
    question: 'Can Corqon work for distributed teams?',
    answer: 'Yes. Distributed teams often face higher fragmentation and context switching. Corqon can help identify instability patterns and support leadership actions to protect focus.',
    tags: ['operations', 'scaling'],
  },
  {
    id: 'can-corqon-support-multiple-departments',
    question: 'Can Corqon support multiple departments?',
    answer: 'Yes. Corqon is designed for multiple teams and business units. Insights remain system-level and can be segmented by team structure.',
    tags: ['operations', 'scaling'],
  },
  {
    id: 'how-do-we-get-started',
    question: 'How do we get started?',
    answer: 'Start with a walkthrough to confirm goals, data sources, and governance. Then connect the minimum signals and run a short baseline period. After that you receive weekly briefs and recommended actions.',
    tags: ['onboarding', 'implementation'],
  },
  {
    id: 'how-long-until-we-see-value',
    question: 'How long until we see value?',
    answer: 'Many teams see useful signals quickly once data is connected. The biggest value comes when actions are implemented and tracked over several weeks. We focus on early clarity and sustained execution.',
    tags: ['onboarding', 'outcomes'],
  },
  {
    id: 'what-does-pilot-look-like',
    question: 'What does a pilot look like?',
    answer: 'A pilot typically focuses on a defined scope, a few teams, and a clear measurement plan. You validate signal quality, workflow fit, and decision value. Then you decide on expansion.',
    tags: ['onboarding', 'implementation'],
  },
  {
    id: 'who-should-own-corqon-internally',
    question: 'Who should own Corqon internally?',
    answer: 'Usually a partnership between HR and an operational leader works best. HR ensures governance and adoption, operations ensures actions happen. Ownership depends on your structure.',
    tags: ['adoption', 'leadership', 'hr'],
  },
  {
    id: 'what-do-managers-get-out-of-it',
    question: 'What do managers get out of it?',
    answer: 'Managers get clearer weekly signals about fragmentation, disruption, and risk trends. They also get recommended actions and playbooks. It helps them act earlier and reduce avoidable firefighting.',
    tags: ['leadership', 'outcomes'],
  },
  {
    id: 'how-do-we-avoid-misuse',
    question: 'How do we avoid misuse?',
    answer: 'Set clear governance: team-level use, no individual scoring, and defined owners. Communicate purpose and boundaries. Corqon should support better operating conditions, not punitive monitoring.',
    tags: ['governance', 'adoption'],
  },
  {
    id: 'what-can-ai-assistant-do',
    question: 'What can the AI assistant do?',
    answer: 'It helps interpret the weekly briefing, clarify what changed, and propose next steps. It can explain drivers, suggest leadership actions, and summarize tradeoffs. It is designed to make the briefing interactive.',
    tags: ['ai', 'briefing', 'assistant'],
  },
  {
    id: 'can-assistant-answer-questions-about-specific-week',
    question: 'Can the assistant answer questions about a specific week?',
    answer: 'Yes. The assistant can be prompted with the selected week context and respond with an explanation and recommended actions. It should follow the same logic and typing behavior as normal chat responses.',
    tags: ['ai', 'briefing', 'assistant'],
  },
  {
    id: 'what-should-i-ask-assistant-first',
    question: 'What should I ask the assistant first?',
    answer: 'Ask what changed and why it matters. Then ask for the top three actions for leadership this week. Finally ask what risks to watch next week.',
    tags: ['ai', 'briefing', 'assistant'],
  },
  {
    id: 'does-assistant-access-employee-personal-data',
    question: 'Does the assistant access employee personal data?',
    answer: 'The assistant is intended to operate on system-level information and configured signals. It should not expose individual employee data. If you have strict requirements, confirm configuration during procurement.',
    tags: ['ai', 'privacy', 'assistant'],
  },
  {
    id: 'how-do-you-prevent-assistant-hallucinating',
    question: 'How do you prevent the assistant from hallucinating?',
    answer: 'Use it as decision support, not a source of absolute truth. The best setup ties assistant answers to the underlying weekly signals and playbooks. If you need strict sourcing, we can discuss guardrails.',
    tags: ['ai', 'assistant', 'governance'],
  },
  {
    id: 'what-does-fragmentation-mean',
    question: 'What does "fragmentation" mean here?',
    answer: 'Fragmentation is when work is split into too many small segments, often driven by meetings, context switching, and interruptions. It reduces deep focus and increases coordination overhead. Corqon highlights when fragmentation rises and where.',
    tags: ['signals', 'definitions', 'performance'],
  },
  {
    id: 'what-does-disruption-mean',
    question: 'What does "disruption" mean?',
    answer: 'Disruption refers to volatility in plans and workflows, like last-minute changes, reactive work, and unstable scheduling. It creates cognitive strain and rework. Corqon detects trend changes and flags risk early.',
    tags: ['signals', 'definitions', 'performance'],
  },
  {
    id: 'what-is-energy-direction',
    question: 'What is "energy direction"?',
    answer: 'It is a directional trend signal at team level, rising, stable, or declining. It is meant to detect early risk before absence or burnout spikes. It is a system signal, not an individual measure.',
    tags: ['signals', 'definitions'],
  },
  {
    id: 'what-is-hr-friction',
    question: 'What is "HR friction"?',
    answer: 'HR friction refers to aggregated patterns like short-term absence cycles, recovery duration, and repeated strain indicators. It can validate operational signals and help prioritize interventions. Exact sources depend on your setup.',
    tags: ['signals', 'definitions', 'hr'],
  },
  {
    id: 'what-is-good-weekly-benchmark',
    question: 'What is a good weekly benchmark?',
    answer: 'Benchmarks depend on your operating model and baseline. Corqon focuses on change over time, comparisons across teams, and early warnings. We recommend defining success metrics in the pilot.',
    tags: ['signals', 'outcomes'],
  },
  {
    id: 'can-we-start-small',
    question: 'Can we start small?',
    answer: 'Yes. A pilot with a limited scope is often the best start. You validate signal quality and decision value before expanding.',
    tags: ['onboarding', 'pricing'],
  },
  {
    id: 'is-there-contract-minimum',
    question: 'Is there a contract minimum?',
    answer: 'Commercial terms depend on scope and procurement requirements. We can align contract structure with pilot and rollout phases.',
    tags: ['pricing', 'contract'],
  },
  {
    id: 'how-do-we-drive-adoption',
    question: 'How do we drive adoption?',
    answer: 'Keep outputs simple: weekly brief, Monday plan, and clear owners. Align leadership on which actions are in scope. Adoption improves when teams see changes reflected week to week.',
    tags: ['adoption', 'change-management'],
  },
  {
    id: 'will-employees-push-back',
    question: 'Will employees push back?',
    answer: 'Employees push back when tools feel like surveillance. Corqon is positioned as system improvement with team-level insights. Clear boundaries and communication reduce friction.',
    tags: ['adoption', 'change-management'],
  },
  {
    id: 'what-if-teams-ignore-recommendations',
    question: 'What if teams ignore the recommendations?',
    answer: 'Corqon is most valuable when actions are assigned and tracked. If recommendations are ignored, you still see signals but outcomes will not improve. We recommend lightweight governance and accountability.',
    tags: ['adoption', 'governance'],
  },
  {
    id: 'we-already-have-dashboards',
    question: 'We already have dashboards, why do we need this?',
    answer: 'Dashboards show data, but not always what to do next. Corqon converts signals into prioritized actions and playbooks. It is designed to reduce decision friction.',
    tags: ['product', 'reporting'],
  },
  {
    id: 'is-this-just-another-ai-layer',
    question: 'Is this just another AI layer?',
    answer: 'Corqon uses AI to detect patterns, but the output is operational, weekly, and action-focused. The goal is clarity for leadership and measurable changes. It is not AI for its own sake.',
    tags: ['ai', 'product'],
  },
  {
    id: 'what-if-data-quality-is-messy',
    question: 'What if our data quality is messy?',
    answer: 'Many organizations start with imperfect data. A pilot helps validate what is usable and what is noise. We focus on minimum viable signals first.',
    tags: ['data', 'onboarding'],
  },
  {
    id: 'can-corqon-handle-multiple-countries',
    question: 'Can Corqon handle multiple countries or languages?',
    answer: 'It can support multi-region team structures. Language and localization depend on the product configuration. If localization is required, confirm in scope discussions.',
    tags: ['scaling', 'operations'],
  },
  {
    id: 'how-do-i-request-security-overview',
    question: 'How do I request a security overview?',
    answer: 'Use the request link in the privacy section or email info@corqon.com. Mention your procurement requirements and desired timeline. We will share the relevant documentation.',
    tags: ['security', 'procurement'],
  },
  {
    id: 'how-do-i-book-pilot',
    question: 'How do I book a pilot?',
    answer: 'Use the primary CTA on the site to schedule a walkthrough. We will define pilot scope, data inputs, and success criteria. Then we align on timeline and stakeholders.',
    tags: ['onboarding', 'implementation'],
  },
  {
    id: 'what-is-fastest-next-step',
    question: 'What is the fastest next step?',
    answer: 'Schedule a walkthrough and pick a pilot scope. Bring one HR owner and one operational owner. We will confirm data sources and define what success looks like.',
    tags: ['onboarding', 'implementation'],
  },
  {
    id: 'what-is-intervention-tracker',
    question: 'What is the Intervention Tracker?',
    answer: 'The Intervention Tracker is where leadership actions are assigned, tracked, and reviewed week over week. It makes it clear what was done, by whom, and what changed afterward. This keeps insights tied to execution.',
    tags: ['briefing', 'reporting', 'leadership', 'actions'],
  },
  {
    id: 'what-does-margin-erosion-mean',
    question: 'What does Corqon mean by margin erosion?',
    answer: 'Margin erosion is the output loss caused by rework, instability, and hidden capacity leakage. It shows up as delays, firefighting, and coordination overhead. Corqon highlights patterns that typically drive that erosion.',
    tags: ['performance', 'margins', 'operations'],
  },
  {
    id: 'how-does-corqon-decide-high-impact',
    question: 'How does Corqon decide what is "high impact" this week?',
    answer: 'High impact is based on change in system signals and how strongly they correlate with disruption, rework, or risk patterns. The goal is to prioritize actions that reduce performance loss quickly. Exact weighting depends on configuration and scope.',
    tags: ['insights', 'operations', 'briefing'],
  },
  {
    id: 'can-we-customize-weekly-actions',
    question: 'Can we customize the weekly actions?',
    answer: 'Yes, actions can be tailored to your operating model and leadership preferences. Corqon provides recommended actions, and you can adapt ownership and effort level. The point is to make execution realistic.',
    tags: ['customization', 'briefing', 'leadership', 'actions'],
  },
  {
    id: 'what-is-playbook',
    question: 'What is a "playbook" in Corqon?',
    answer: 'A playbook is a structured response to a recurring pattern, like workload spikes, volatility, or recovery dips. It describes what to change, who should do it, and what outcome to expect. It is meant to be used by managers and HR.',
    tags: ['briefing', 'leadership', 'actions', 'operations'],
  },
  {
    id: 'can-corqon-explain-why-signal-changed',
    question: 'Can Corqon explain why a signal changed?',
    answer: 'Corqon can highlight the most likely drivers behind a change, based on available system signals. It is intended to support decision making, not replace investigation. The assistant can also suggest next steps to validate causes.',
    tags: ['insights', 'signals', 'ai', 'assistant'],
  },
  {
    id: 'can-we-compare-teams-without-blame',
    question: 'Can we compare teams without creating blame?',
    answer: 'Yes, if governance is clear. Use comparisons to spot structural issues, not to rank individuals. Corqon is designed for system improvement and team-level visibility.',
    tags: ['governance', 'operations', 'reporting'],
  },
  {
    id: 'how-does-corqon-handle-small-teams',
    question: 'How does Corqon handle small teams?',
    answer: 'Small teams may require stronger aggregation thresholds to protect privacy and avoid noisy signals. Corqon can be configured to keep reporting system-level. Discuss thresholds during rollout.',
    tags: ['privacy', 'governance', 'operations', 'scaling'],
  },
  {
    id: 'can-we-set-minimum-team-size',
    question: 'Can we set a minimum team size for reporting?',
    answer: 'Yes, minimum thresholds are a common privacy and signal-quality control. This helps prevent identification and reduces volatility in small samples. Align this with your governance model.',
    tags: ['privacy', 'governance', 'operations'],
  },
  {
    id: 'what-does-confidence-mean',
    question: 'What does "confidence" mean in the dashboard?',
    answer: 'Confidence indicates how strongly the system signals support the weekly narrative and actions. It is not absolute truth, but a decision-quality indicator. Higher confidence typically means multiple signals align.',
    tags: ['insights', 'signals', 'reporting'],
  },
  {
    id: 'can-assistant-cite-insight-source',
    question: 'Can the assistant cite where an insight came from?',
    answer: 'If the system is configured with traceable signals, the assistant can reference the underlying signal categories. For strict sourcing, you may want guardrails and structured references. Confirm the sourcing requirements during implementation.',
    tags: ['ai', 'assistant', 'governance', 'insights'],
  },
  {
    id: 'what-if-assistant-gives-wrong-answer',
    question: 'What if the assistant gives an answer that seems wrong?',
    answer: 'Treat it as decision support and validate against the weekly signals. Ask follow-up questions like "What changed compared to last week?" and "Which signal supports this?" If needed, escalate the question to your Corqon contact.',
    tags: ['ai', 'assistant', 'governance'],
  },
  {
    id: 'can-corqon-send-weekly-briefs-email-slack',
    question: 'Can Corqon send weekly briefs by email or Slack?',
    answer: 'Distribution options depend on product configuration and your workflows. Many teams prefer a link-based weekly brief plus an internal cadence. We can align on the preferred distribution during rollout.',
    tags: ['briefing', 'reporting', 'integrations', 'onboarding'],
  },
  {
    id: 'can-we-receive-alerts-mid-week',
    question: 'Can we receive alerts when risk spikes mid-week?',
    answer: 'Alerting depends on how you want to run operations. Corqon is designed around weekly decision cycles, but certain patterns can be flagged sooner. Define alert needs in the pilot scope.',
    tags: ['briefing', 'reporting', 'operations', 'onboarding'],
  },
  {
    id: 'difference-between-workload-and-strain',
    question: 'What is the difference between "workload" and "strain"?',
    answer: 'Workload is the amount of demand. Strain is how demand interacts with fragmentation, disruption, and recovery signals. Two teams can have similar workload and very different strain.',
    tags: ['signals', 'definitions', 'performance'],
  },
  {
    id: 'what-is-recovery-dip',
    question: 'What is "recovery dip"?',
    answer: 'A recovery dip is a signal that the system is not recovering back to baseline, often after peaks of disruption or intensity. It can indicate sustained instability or insufficient recovery windows. It is used to trigger early interventions.',
    tags: ['signals', 'definitions', 'performance'],
  },
  {
    id: 'what-is-planning-volatility',
    question: 'What does "planning volatility" refer to?',
    answer: 'Planning volatility is frequent last-minute change, reactive reprioritization, and unstable scheduling. It increases cognitive load and rework. Corqon highlights when volatility trends upward.',
    tags: ['signals', 'definitions', 'performance'],
  },
  {
    id: 'can-corqon-help-reduce-meetings',
    question: 'Can Corqon help reduce meetings?',
    answer: 'Corqon can highlight fragmentation patterns that often correlate with heavy meeting load and context switching. The output is not "ban meetings," but targeted changes to protect focus. Actions should be adapted to your operating model.',
    tags: ['operations', 'performance', 'actions'],
  },
  {
    id: 'does-corqon-work-for-product-teams',
    question: 'Does Corqon work for product teams?',
    answer: 'Yes, product teams often face interruption and volatility across stakeholders. Corqon can detect system-level patterns that reduce deep work time. It helps leadership tune operating conditions.',
    tags: ['operations', 'scaling'],
  },
  {
    id: 'does-corqon-work-for-consulting-agencies',
    question: 'Does Corqon work for consulting or agencies?',
    answer: 'Yes, especially where margin depends on predictable execution and low rework. Corqon helps detect instability and hidden capacity loss. It supports interventions that protect delivery.',
    tags: ['operations', 'scaling'],
  },
  {
    id: 'what-should-leadership-review-monday',
    question: 'What should leadership review each Monday?',
    answer: 'Review the weekly change summary, top risks, and the Monday plan actions. Assign owners and set a simple check-in moment. Track whether signals improve in the following weeks.',
    tags: ['briefing', 'leadership', 'actions'],
  },
  {
    id: 'can-corqon-quantify-rework',
    question: 'Can Corqon quantify rework?',
    answer: 'Corqon can surface patterns that typically drive rework and coordination overhead. Exact quantification depends on which operational signals are connected. In a pilot, you can define a practical measurement approach.',
    tags: ['insights', 'operations', 'performance', 'onboarding'],
  },
  {
    id: 'can-corqon-estimate-absenteeism-cost',
    question: 'Can Corqon estimate cost of absenteeism risk?',
    answer: 'Corqon can help identify early risk patterns and where to intervene. Cost estimation depends on your internal HR and finance assumptions. We recommend defining a simple model during rollout.',
    tags: ['insights', 'operations', 'hr', 'finance', 'onboarding'],
  },
  {
    id: 'expected-time-commitment-hr',
    question: 'What is the expected time commitment for HR?',
    answer: 'HR time is usually focused on governance, reviewing weekly insights, and aligning actions with leadership. A lightweight cadence often works best. Exact effort depends on scope and rollout phase.',
    tags: ['adoption', 'hr', 'leadership', 'onboarding'],
  },
  {
    id: 'expected-time-commitment-managers',
    question: 'What is the expected time commitment for managers?',
    answer: 'Managers typically use Corqon to select and execute a few high-leverage actions each week. The goal is to reduce firefighting, not add workload. Effort should be practical and time-boxed.',
    tags: ['adoption', 'leadership', 'actions'],
  },
  {
    id: 'can-we-run-corqon-one-department-first',
    question: 'Can we run Corqon in one department first?',
    answer: 'Yes, a focused pilot is often the best start. Choose a department where volatility or rework is felt and leadership is engaged. Then expand once signal quality and workflow fit are proven.',
    tags: ['onboarding', 'implementation', 'scaling'],
  },
  {
    id: 'how-does-corqon-handle-seasonality',
    question: 'How does Corqon handle seasonality?',
    answer: 'Seasonality is addressed by tracking trends over time and comparing changes relative to baseline. The weekly brief should distinguish expected cycles from abnormal spikes. Pilot design should include a baseline period.',
    tags: ['insights', 'signals', 'onboarding'],
  },
  {
    id: 'can-corqon-support-mergers-reorganizations',
    question: 'Can Corqon support mergers or reorganizations?',
    answer: 'Yes, reorgs often increase volatility and coordination load. Corqon can help detect where instability rises and which teams need support. Governance is critical during these periods.',
    tags: ['operations', 'scaling', 'governance'],
  },
  {
    id: 'difference-between-signals-and-insights',
    question: 'What is the difference between "signals" and "insights"?',
    answer: 'Signals are measurable patterns in the operating system of work. Insights interpret what the signals likely mean and why it matters. Corqon aims to turn signals into decision-grade actions.',
    tags: ['signals', 'definitions', 'insights'],
  },
  {
    id: 'can-we-edit-weekly-narrative',
    question: 'Can we edit or override the weekly narrative?',
    answer: 'Many leadership teams want the ability to add context or notes. Whether editing is available depends on configuration. Even without editing, the assistant can help refine interpretation.',
    tags: ['customization', 'briefing', 'ai', 'assistant'],
  },
  {
    id: 'what-does-privacy-safe-aggregation-mean',
    question: 'What does "privacy-safe aggregation" mean in practice?',
    answer: 'It means insights are computed at a level that protects individual identity. It also means avoiding employee-level scoring and applying governance thresholds. The exact setup should be confirmed during rollout.',
    tags: ['privacy', 'governance', 'onboarding'],
  },
  {
    id: 'do-you-use-employee-communications-content',
    question: 'Do you use employee communications content?',
    answer: 'Corqon\'s intent is to work with operational signals and aggregated patterns, not employee message content. Exact inputs depend on the sources you connect and your governance. Confirm the data scope during procurement.',
    tags: ['privacy', 'data', 'governance', 'procurement'],
  },
  {
    id: 'where-is-data-hosted',
    question: 'Where is data hosted?',
    answer: 'Hosting and data residency depend on your deployment and vendor setup. If you have strict residency requirements, raise them during procurement. We can outline options and constraints.',
    tags: ['privacy', 'security', 'compliance', 'procurement'],
  },
  {
    id: 'do-you-use-sub-processors',
    question: 'Do you use sub-processors?',
    answer: 'Many SaaS products rely on vetted vendors for hosting and analytics. If required, we can provide an overview for procurement. The exact list depends on the final deployment configuration.',
    tags: ['privacy', 'security', 'compliance', 'procurement'],
  },
  {
    id: 'what-is-incident-response-process',
    question: 'What is your incident response process?',
    answer: 'We aim to follow standard security practices for monitoring and incident handling. Procurement can request a security overview and escalation path. Email info@corqon.com for documentation requests.',
    tags: ['security', 'procurement', 'compliance'],
  },
  {
    id: 'can-we-request-penetration-test-report',
    question: 'Can we request a penetration test report?',
    answer: 'If you require specific security evidence, we can discuss what is available. Requirements vary by customer and scope. We can provide a security overview and align on procurement needs.',
    tags: ['security', 'procurement', 'compliance'],
  },
  {
    id: 'can-assistant-be-restricted-to-topics',
    question: 'Can the assistant be restricted to certain topics?',
    answer: 'Yes, topic restrictions and guardrails can be important for governance. The exact controls depend on product configuration. Define constraints during rollout.',
    tags: ['ai', 'assistant', 'governance', 'customization'],
  },
  {
    id: 'can-corqon-be-used-for-performance-evaluation',
    question: 'Can Corqon be used for performance evaluation?',
    answer: 'Corqon is designed for system improvement, not individual evaluation. Using it for punitive monitoring increases risk and reduces trust. Governance should keep it leadership and system-focused.',
    tags: ['governance', 'operations'],
  },
  {
    id: 'what-is-best-first-pilot-metric',
    question: 'What is the best first pilot metric?',
    answer: 'Pick something operational and observable, like reduced volatility, reduced rework indicators, or improved focus stability trends. Then track weekly actions and signal movement. Define success in the pilot kickoff.',
    tags: ['onboarding', 'implementation', 'outcomes'],
  },
  {
    id: 'how-do-we-avoid-dashboard-fatigue',
    question: 'How do we avoid "dashboard fatigue"?',
    answer: 'Keep the workflow weekly and action-based. Focus on the Monday plan and intervention tracking rather than browsing metrics. Corqon is intended to reduce noise, not create more.',
    tags: ['adoption', 'briefing', 'reporting'],
  },
  {
    id: 'can-corqon-support-executive-reporting',
    question: 'Can Corqon support executive reporting?',
    answer: 'Yes, the weekly brief can be used as an executive summary of operational strain and risk. The key is clarity, changes over time, and what leadership is doing next. Tailor the format to your cadence.',
    tags: ['briefing', 'reporting', 'leadership'],
  },
  {
    id: 'can-we-connect-corqon-to-bi-tools',
    question: 'Can we connect Corqon to our BI tools?',
    answer: 'Integration with BI depends on your reporting needs and data governance. Some teams prefer Corqon as the action layer and keep BI separate. Discuss export needs in procurement.',
    tags: ['integrations', 'reporting', 'procurement'],
  },
  {
    id: 'what-does-system-level-mean',
    question: 'What does "system-level" mean in Corqon?',
    answer: 'It means patterns are derived from how work operates across teams, not from evaluating individuals. The focus is on structures that create instability, fragmentation, and rework. That is where hidden margin loss often starts.',
    tags: ['signals', 'definitions', 'operations', 'performance'],
  },
  {
    id: 'does-corqon-require-employee-participation',
    question: 'Does Corqon require employee participation?',
    answer: 'Corqon can be valuable with minimal employee effort if the right operational signals are connected. Participation requirements depend on your chosen inputs and governance. A pilot can confirm the lowest-friction setup.',
    tags: ['adoption', 'data', 'operations', 'onboarding'],
  },
  {
    id: 'can-corqon-help-onboarding-strain-fast-growth',
    question: 'Can Corqon help with onboarding strain in fast growth?',
    answer: 'Rapid onboarding can increase coordination overhead and volatility. Corqon can highlight where instability rises and where support is needed. Actions should focus on process clarity and workload design.',
    tags: ['operations', 'scaling', 'hr'],
  },
  {
    id: 'can-corqon-help-reduce-churn-risk',
    question: 'Can Corqon help reduce churn risk?',
    answer: 'Corqon focuses on early signals of systemic strain that can contribute to churn. It is not a churn predictor for individuals. The goal is to improve operating conditions before risk compounds.',
    tags: ['operations', 'performance', 'hr'],
  },
  {
    id: 'what-happens-if-we-change-org-structure',
    question: 'What happens if we change our org structure?',
    answer: 'Team structures can be updated so aggregation remains accurate. During transitions, signal interpretation should be cautious. The weekly brief should reflect changes in structure and scope.',
    tags: ['operations', 'scaling', 'customization'],
  },
  {
    id: 'who-is-kaya-gunes',
    question: 'Who is Kaya Güneş',
    answer: 'Kaya Güneş is Co Founder and CEO of CORQON. As one of the company\'s two founders, he sets the strategic direction and leads execution across product, brand, and go to market. He is the creative and planning half of CORQON, responsible for turning vision into a coherent roadmap, shaping the end to end user experience, and ensuring every release meets CORQON\'s premium standard.\n\nKaya combines high level strategy with hands on delivery. He drives planning cadence, prioritization, and sprint execution, while also owning core narratives and positioning for enterprise stakeholders. Under his leadership, CORQON stays focused, ships consistently, and presents with the clarity and credibility required to win trust at the executive level.',
    tags: ['leadership'],
  },
  {
    id: 'who-is-dennis-de-kort',
    question: 'Who is Dennis de Kort',
    answer: 'Dennis de Kort is Co Founder and CEO of CORQON. As one of the company\'s two founders, he defines CORQON\'s analytical direction and leads the development of the measurement, insights, and decision frameworks that power the platform. He is the analytical mind behind the corporation, responsible for ensuring CORQON\'s outputs are rigorous, defensible, and actionable at executive level.\n\nDennis translates complex signals into clear, board ready intelligence. He drives KPI architecture, benchmarking logic, reporting methodology, and the underlying data models that connect workforce patterns to business impact. With a strong focus on accuracy and accountability, he ensures CORQON delivers insights leaders can trust, decisions they can justify, and outcomes they can measure.',
    tags: ['leadership'],
  },
  {
    id: 'what-is-corqon-in-one-sentence',
    question: 'What is CORQON in one sentence?',
    answer: 'CORQON connects operational data streams and turns system signals into weekly, decision ready actions that reduce hidden productivity loss and margin erosion.',
    tags: ['product', 'overview'],
  },
  {
    id: 'what-are-system-signals',
    question: 'What does CORQON mean by "system signals"?',
    answer: 'System signals are patterns in how work runs across teams, such as volatility, fragmentation, and recovery trends. They are used to guide leadership decisions at team level, not to evaluate individuals.',
    tags: ['signals', 'definitions'],
  },
  {
    id: 'what-is-main-output',
    question: 'What is the main output CORQON provides?',
    answer: 'A weekly briefing that explains what changed, why it matters, and what to do next. It also includes a Monday plan with owners, effort level, and expected outcomes.',
    tags: ['briefing', 'reporting'],
  },
  {
    id: 'difference-dashboard-weekly-briefing',
    question: 'What is the difference between the dashboard and the weekly briefing?',
    answer: 'The dashboard shows current signals and trends. The weekly briefing converts those signals into a narrative and prioritized actions so leadership can execute.',
    tags: ['briefing', 'dashboard', 'reporting'],
  },
  {
    id: 'what-does-corqon-help-coo-do',
    question: 'What does CORQON help a COO do?',
    answer: 'It helps a COO spot instability and rework patterns early and assign corrective actions. It turns operational noise into a weekly execution plan that protects delivery and margins.',
    tags: ['leadership', 'operations'],
  },
  {
    id: 'what-does-corqon-help-hr-do',
    question: 'What does CORQON help HR do?',
    answer: 'It helps HR link workforce patterns to operational conditions and interventions. It supports governance and early risk response without individual scoring.',
    tags: ['hr', 'leadership'],
  },
  {
    id: 'what-does-corqon-help-team-leads-do',
    question: 'What does CORQON help team leads do?',
    answer: 'It helps team leads reduce fragmentation, stabilize planning, and avoid recurring firefighting. The focus is on practical weekly actions, not constant monitoring.',
    tags: ['leadership', 'operations'],
  },
  {
    id: 'how-does-corqon-support-executive-reporting',
    question: 'How does CORQON support executive reporting?',
    answer: 'It creates a clear weekly narrative with trend movement and action ownership. It is designed to be board ready and defensible, not just a dashboard screenshot.',
    tags: ['briefing', 'reporting', 'leadership'],
  },
  {
    id: 'what-does-fragmentation-mean-corqon',
    question: 'What does "fragmentation" mean in CORQON?',
    answer: 'Fragmentation is when work is broken into too many small pieces, often due to meetings, interruptions, and context switching. It reduces deep work and increases coordination overhead.',
    tags: ['signals', 'definitions'],
  },
  {
    id: 'what-does-disruption-mean-corqon',
    question: 'What does "disruption" mean in CORQON?',
    answer: 'Disruption is volatility in planning and execution, such as last minute changes and reactive reprioritization. It typically increases rework and cognitive load.',
    tags: ['signals', 'definitions'],
  },
  {
    id: 'what-does-predictability-mean',
    question: 'What does "predictability" mean here?',
    answer: 'Predictability reflects how stable work rhythms are over time. Higher predictability usually supports better focus, fewer surprises, and lower coordination overhead.',
    tags: ['signals', 'definitions'],
  },
  {
    id: 'what-does-capacity-leakage-mean',
    question: 'What does "capacity leakage" mean?',
    answer: 'Capacity leakage is output lost to coordination, context switching, rework, and instability. It is often invisible until deadlines slip or margins shrink.',
    tags: ['signals', 'definitions', 'performance'],
  },
  {
    id: 'what-is-intervention-tracker-used-for',
    question: 'What is the Intervention Tracker used for?',
    answer: 'It tracks which interventions were chosen, who owns them, and what changed afterward. It is the bridge between insights and measurable execution.',
    tags: ['briefing', 'actions', 'leadership'],
  },
  {
    id: 'what-does-confidence-label-mean',
    question: 'What does the "confidence" label mean?',
    answer: 'Confidence indicates how strongly multiple signals align with the weekly conclusion. It helps leadership prioritize which actions are most defensible to execute first.',
    tags: ['insights', 'signals'],
  },
  {
    id: 'how-does-corqon-decide-top-actions',
    question: 'How does CORQON decide the top actions each week?',
    answer: 'Actions are prioritized by signal movement, risk relevance, and expected operational impact. The goal is to propose steps leadership can actually execute, not theoretical advice.',
    tags: ['briefing', 'actions', 'insights'],
  },
  {
    id: 'can-we-edit-monday-plan-actions',
    question: 'Can we edit the Monday plan actions?',
    answer: 'Yes, ownership and execution details can be adjusted to match your operating model. CORQON provides recommendations, but leadership decides what is realistic.',
    tags: ['briefing', 'actions', 'customization'],
  },
  {
    id: 'what-is-playbook-inside-corqon',
    question: 'What is a playbook inside CORQON?',
    answer: 'A playbook is a repeatable response to a known pattern, like rising volatility or recovery dips. It outlines what to do, who should do it, and what outcome to expect.',
    tags: ['briefing', 'actions', 'operations'],
  },
  {
    id: 'can-corqon-run-without-hr-data',
    question: 'Can CORQON run without HR data?',
    answer: 'Often yes. Operational signals can already reveal fragmentation and instability patterns. HR data can be used as an optional validation layer if you choose.',
    tags: ['data', 'integrations', 'hr'],
  },
  {
    id: 'do-you-track-individual-employees-corqon',
    question: 'Do you track individual employees?',
    answer: 'No. CORQON is designed for team and system level insights and avoids individual scoring. Governance should reinforce this boundary.',
    tags: ['privacy', 'governance'],
  },
  {
    id: 'can-manager-use-corqon-for-individual-performance',
    question: 'Can a manager use CORQON for individual performance evaluation?',
    answer: 'CORQON is not designed for that purpose. It is intended to improve operating conditions at team level. Misuse increases risk and reduces trust.',
    tags: ['governance', 'privacy'],
  },
  {
    id: 'how-does-corqon-stay-privacy-safe',
    question: 'How does CORQON stay privacy safe?',
    answer: 'By focusing on aggregation, data minimization, and system level outputs. The exact thresholds and governance are aligned during rollout.',
    tags: ['privacy', 'governance'],
  },
  {
    id: 'does-corqon-read-employee-messages',
    question: 'Does CORQON read employee messages or content?',
    answer: 'CORQON is intended to operate on operational signals and aggregated patterns, not personal message content. The exact inputs depend on what sources you connect and approve.',
    tags: ['privacy', 'data'],
  },
  {
    id: 'what-documentation-can-procurement-request',
    question: 'What documentation can procurement request?',
    answer: 'Privacy policy, cookie policy, and procurement level security overview. If you have specific requirements, email info@corqon.com and we will align on what is needed.',
    tags: ['procurement', 'compliance'],
  },
  {
    id: 'do-you-provide-data-processing-agreement',
    question: 'Do you provide a Data Processing Agreement?',
    answer: 'A DPA can be provided for procurement review. It documents processing purpose, responsibilities, and controls.',
    tags: ['privacy', 'compliance', 'procurement'],
  },
  {
    id: 'where-is-data-hosted-corqon',
    question: 'Where is data hosted?',
    answer: 'Hosting and residency depend on the deployment and vendor setup. If you require specific regions or constraints, raise them during procurement and pilot scoping.',
    tags: ['privacy', 'security', 'procurement'],
  },
  {
    id: 'do-you-support-sso-corqon',
    question: 'Do you support SSO?',
    answer: 'If SSO is required, it can be discussed as part of rollout. Support depends on your identity provider and configuration.',
    tags: ['security', 'integrations'],
  },
  {
    id: 'can-access-be-restricted-by-role',
    question: 'Can access be restricted by role?',
    answer: 'Yes, role based access is a standard expectation for leadership tools. The exact roles should align to your governance model.',
    tags: ['security', 'governance'],
  },
  {
    id: 'can-we-export-reports',
    question: 'Can we export reports?',
    answer: 'Export needs vary by customer governance and analytics workflows. We can align on the right export approach during procurement and implementation.',
    tags: ['data', 'reporting', 'governance'],
  },
  {
    id: 'how-long-does-implementation-take',
    question: 'How long does implementation take?',
    answer: 'It depends on sources, governance, and scope. Many teams start with a minimal signal set to establish a baseline quickly, then expand.',
    tags: ['onboarding', 'implementation'],
  },
  {
    id: 'what-is-minimum-needed-to-start',
    question: 'What is the minimum needed to start?',
    answer: 'A clear team structure for aggregation and enough operational signals to detect volatility and fragmentation trends. HR data can be optional.',
    tags: ['onboarding', 'data'],
  },
  {
    id: 'what-does-pilot-look-like',
    question: 'What does a pilot look like?',
    answer: 'A pilot usually covers a defined scope with clear success criteria, minimal integrations, and weekly review cadence. It validates signal quality, workflow fit, and decision value.',
    tags: ['onboarding', 'implementation'],
  },
  {
    id: 'how-quickly-can-we-see-value',
    question: 'How quickly can we see value?',
    answer: 'Useful signals can appear soon after connection and baseline. The strongest value comes when weekly actions are executed and tracked over several weeks.',
    tags: ['onboarding', 'outcomes'],
  },
  {
    id: 'who-should-own-corqon-internally',
    question: 'Who should own CORQON internally?',
    answer: 'Typically an HR owner for governance and an operational owner for execution. Ownership depends on your structure, but it works best when actions have clear owners.',
    tags: ['adoption', 'leadership', 'hr'],
  },
  {
    id: 'how-do-we-communicate-corqon-internally',
    question: 'How do we communicate CORQON internally?',
    answer: 'Position it as improving operating conditions, not monitoring individuals. Explain team level aggregation and the weekly action focus. Keep boundaries explicit.',
    tags: ['adoption', 'communication'],
  },
  {
    id: 'what-does-board-ready-mean',
    question: 'What does "board ready" mean in CORQON context?',
    answer: 'Insights are structured to be defensible, measurable, and tied to actions. The goal is clarity leadership can stand behind, not vague wellbeing statements.',
    tags: ['briefing', 'reporting', 'leadership'],
  },
  {
    id: 'what-should-we-ask-assistant-first',
    question: 'What should we ask the assistant first?',
    answer: 'Ask what changed compared to last week and why it matters. Then ask for the top three actions and who should own them. Finally ask what risks to watch next week.',
    tags: ['ai', 'assistant'],
  },
  {
    id: 'can-assistant-answer-questions-about-specific-week',
    question: 'Can the assistant answer questions about a specific week?',
    answer: 'Yes, it can interpret a selected week and explain drivers and recommended actions. It should stay consistent with the weekly signals and playbooks.',
    tags: ['ai', 'assistant', 'briefing'],
  },
  {
    id: 'why-does-corqon-focus-on-weekly-cadence',
    question: 'Why does CORQON focus on weekly cadence?',
    answer: 'Weekly cadence matches leadership decision cycles and avoids constant noise. It creates a stable rhythm for execution and measurement.',
    tags: ['briefing', 'operations'],
  },
  {
    id: 'what-is-margin-erosion-practical-terms',
    question: 'What is "margin erosion" in practical terms?',
    answer: 'It is the business impact of instability, rework, and capacity leakage. You see it as missed deadlines, lower delivery quality, and higher cost to produce the same output.',
    tags: ['performance', 'margins'],
  },
  {
    id: 'can-corqon-help-reduce-rework',
    question: 'Can CORQON help reduce rework?',
    answer: 'CORQON surfaces patterns that commonly drive rework, like disruption and fragmentation. Actions typically focus on stabilizing planning and protecting focus windows.',
    tags: ['operations', 'performance'],
  },
  {
    id: 'can-corqon-help-reduce-meeting-overload',
    question: 'Can CORQON help reduce meeting overload?',
    answer: 'It can reveal fragmentation patterns that often correlate with meeting density and context switching. The output is targeted interventions, not blanket rules.',
    tags: ['operations', 'performance'],
  },
  {
    id: 'can-corqon-support-distributed-teams',
    question: 'Can CORQON support distributed teams?',
    answer: 'Yes. Distributed work often increases coordination overhead and fragmentation. CORQON helps leadership see where stability and focus are breaking down.',
    tags: ['operations', 'scaling'],
  },
  {
    id: 'can-corqon-support-multiple-business-units',
    question: 'Can CORQON support multiple business units?',
    answer: 'Yes, as long as team structures and governance are defined. Insights remain system level and can be segmented by unit or team structure.',
    tags: ['operations', 'scaling'],
  },
  {
    id: 'what-happens-if-data-quality-messy',
    question: 'What happens if our data quality is messy?',
    answer: 'Many teams start with imperfect data. A pilot helps validate what is usable and what is noise. CORQON focuses on minimum viable signals first.',
    tags: ['data', 'onboarding'],
  },
  {
    id: 'how-does-corqon-handle-reorganizations',
    question: 'How does CORQON handle reorganizations?',
    answer: 'Reorgs often increase volatility and coordination load. CORQON can help detect where instability rises and where support is needed, with careful interpretation during transitions.',
    tags: ['operations', 'scaling'],
  },
  {
    id: 'how-does-corqon-avoid-becoming-another-dashboard',
    question: 'How does CORQON avoid becoming another dashboard?',
    answer: 'It is designed around actions, ownership, and weekly review. The Monday plan and Intervention Tracker keep focus on execution, not browsing metrics.',
    tags: ['product', 'briefing'],
  },
  {
    id: 'what-is-difference-between-signals-and-kpis',
    question: 'What is the difference between signals and KPIs?',
    answer: 'KPIs measure outcomes. Signals detect early patterns that often drive outcomes. CORQON uses signals to guide intervention before KPIs degrade.',
    tags: ['signals', 'definitions'],
  },
  {
    id: 'how-can-we-contact-corqon',
    question: 'How can we contact CORQON?',
    answer: 'Email info@corqon.com for procurement questions, pilot scoping, or documentation requests. The fastest next step is a short walkthrough to confirm fit and scope.',
    tags: ['onboarding', 'procurement'],
  },
  {
    id: 'how-do-i-contact-corqon-procurement',
    question: 'How do I contact Corqon for procurement questions?',
    answer: 'Email info@corqon.com with your requirements and timeline. Include any security, privacy, or integration constraints you need addressed. We will respond with the relevant materials.',
    tags: ['procurement', 'onboarding'],
  },
  {
    id: 'what-is-fastest-way-to-validate-corqon',
    question: 'What is the fastest way to validate Corqon for our company?',
    answer: 'Start with a pilot scope that is small but meaningful, with clear success criteria. Connect the minimum viable signals, establish a baseline, and run weekly actions. Then decide on expansion based on evidence.',
    tags: ['onboarding', 'implementation', 'outcomes'],
  },
  {
    id: 'smalltalk-hello',
    question: 'hello',
    answer: 'Hi. Welcome to CORQON. Are you here to explore the weekly briefing, the dashboard signals, or privacy and procurement?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-hi',
    question: 'hi',
    answer: 'Hi there. What would you like to understand first: what CORQON measures, what it outputs each week, or how implementation works?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-hey',
    question: 'hey',
    answer: 'Hey. Happy to help. Are you looking at CORQON from an HR, operations, or leadership perspective?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-good-morning',
    question: 'good morning',
    answer: 'Good morning. What are you trying to solve right now: instability, rework, productivity loss, or absence risk?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-good-afternoon',
    question: 'good afternoon',
    answer: 'Good afternoon. What should we focus on: the weekly briefing, the Monday plan actions, or the data signals behind it?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-good-evening',
    question: 'good evening',
    answer: 'Good evening. Want a quick overview of CORQON, or do you have a specific question about the dashboard?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-hello-there',
    question: 'hello there',
    answer: 'Hello. If you tell me your role and team size, I can point you to the most relevant part of the product.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-hey-corqon',
    question: 'hey corqon',
    answer: 'Hey. What would you like to explore: the data streams, the weekly briefing, or the assistant workflow?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-yo',
    question: 'yo',
    answer: 'Hi. What are you hoping to improve: delivery stability, focus time, or early risk detection?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-sup',
    question: 'sup',
    answer: 'Hi. Tell me one thing that feels broken this week and I will suggest what to look at in CORQON.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-how-are-you',
    question: 'how are you',
    answer: 'Doing well, thanks. What can I help you with today: product overview, implementation, or procurement questions?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-how-are-you-doing',
    question: 'how are you doing',
    answer: 'Good, thanks. Are you here to see a sample weekly briefing or to understand how the signals are measured?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-how-is-it-going',
    question: 'how is it going',
    answer: 'Going well. What is the main challenge in your org right now: volatility, fragmentation, or rework?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-you-there',
    question: 'you there',
    answer: 'Yes. What would you like to ask about CORQON?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-are-you-there',
    question: 'are you there',
    answer: 'I am here. Do you want a quick overview or do you have a specific question about the weekly brief?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-can-you-help-me',
    question: 'can you help me',
    answer: 'Yes. Tell me what you are trying to achieve, and I will point you to the relevant CORQON section and next step.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-i-need-help',
    question: 'i need help',
    answer: 'Sure. Are you trying to understand what CORQON measures, how privacy works, or what a pilot looks like?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-help',
    question: 'help',
    answer: 'I can help. What is your priority: reduce rework, stabilize planning, or prevent hidden capacity loss?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-i-have-a-question',
    question: 'i have a question',
    answer: 'Go for it. What is your question about: product, pricing, privacy, or implementation?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-can-i-ask-something',
    question: 'can i ask something',
    answer: 'Of course. Ask away. If you share your role, I can tailor the answer.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-what-can-you-do',
    question: 'what can you do',
    answer: 'I can explain CORQON, interpret the weekly briefing, and suggest next steps for leadership. What do you want to start with?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-what-are-you',
    question: 'what are you',
    answer: 'I am the CORQON site assistant. I can help you understand the dashboard, weekly briefing, and how CORQON detects systemic performance loss.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-who-are-you',
    question: 'who are you',
    answer: 'I am the CORQON assistant. Tell me what you want to learn and I will guide you.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-are-you-a-bot',
    question: 'are you a bot',
    answer: 'I am an assistant designed to help you navigate CORQON. If you tell me what you are evaluating, I can make this quick.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-are-you-human',
    question: 'are you human',
    answer: 'I am an AI assistant. I can still give clear, practical answers. What are you trying to solve in your organization?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-can-you-explain-corqon',
    question: 'can you explain corqon',
    answer: 'CORQON connects operational data streams and detects systemic performance loss early. It turns signals into a weekly brief and leadership actions. Want the short version or the practical workflow?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-tell-me-about-corqon',
    question: 'tell me about corqon',
    answer: 'CORQON helps leadership spot volatility, fragmentation, and rework patterns before they hit output and margins. Would you like a sample weekly briefing or an implementation overview?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-what-is-this-site',
    question: 'what is this site',
    answer: 'This is the CORQON product site. You can explore how we read organizational signals, see a sample weekly brief, and understand privacy.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-what-is-corqon',
    question: 'what is corqon',
    answer: 'CORQON is a system intelligence layer for leadership. It connects data streams to detect patterns that quietly erode productivity and margins.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-what-do-you-measure',
    question: 'what do you measure',
    answer: 'We focus on system level patterns like fragmentation, disruption, predictability, and validation signals. If you share your setup, I can explain what applies.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-how-does-it-work',
    question: 'how does it work',
    answer: 'We connect the minimum viable signals, establish a baseline, then produce weekly briefs and actions. Want the quick pilot version or the full implementation version?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-what-should-i-ask-you',
    question: 'what should i ask you',
    answer: 'Ask what changed this week, why it matters, and the top three actions with owners. Want me to propose a first question for your context?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-where-do-i-start',
    question: 'where do i start',
    answer: 'Start with the weekly briefing sample, then look at the Monday plan actions. Are you evaluating CORQON for HR, operations, or leadership?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-i-am-just-browsing',
    question: 'i am just browsing',
    answer: 'No problem. If you want, I can summarize CORQON in 30 seconds or guide you to the most relevant section based on your role.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-i-am-interested',
    question: 'i am interested',
    answer: 'Great. What outcome matters most: stability, focus, reduced rework, or early risk detection?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-i-want-a-demo',
    question: 'i want a demo',
    answer: 'We can help you get a walkthrough. Do you want to start with a pilot scope, or first see a sample weekly briefing?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-can-i-book-a-call',
    question: 'can i book a call',
    answer: 'Yes. The site CTA is the fastest route. If you tell me your team size and role, I can suggest what to bring to the call.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-can-we-talk',
    question: 'can we talk',
    answer: 'Yes. What is the main problem you want to solve right now?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-i-want-to-talk-to-someone',
    question: 'i want to talk to someone',
    answer: 'If you want a direct contact route, you can email info@corqon.com. Before that, what would you like clarified: privacy, implementation, or expected outcomes?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-thanks',
    question: 'thanks',
    answer: 'You are welcome. Want to go one level deeper on signals, actions, or rollout?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-thank-you',
    question: 'thank you',
    answer: 'Happy to help. Do you want a quick overview of the weekly briefing flow?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-appreciate-it',
    question: 'appreciate it',
    answer: 'Anytime. What is the next question on your mind?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-cool',
    question: 'cool',
    answer: 'Glad it helps. Want to see how the Monday plan ties to business impact?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-nice',
    question: 'nice',
    answer: 'Thanks. If you tell me your industry and team structure, I can make the explanation more specific.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-ok',
    question: 'ok',
    answer: 'Great. What should we tackle next?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-awesome',
    question: 'awesome',
    answer: 'Good to hear. Do you want to focus on implementation timeline or procurement readiness?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-great',
    question: 'great',
    answer: 'Great. What is your biggest constraint: data access, governance, or leadership bandwidth?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-can-you-summarize',
    question: 'can you summarize',
    answer: 'CORQON detects systemic performance loss early and turns it into weekly leadership actions. Want a one minute overview or a sample week walkthrough?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-give-me-the-short-version',
    question: 'give me the short version',
    answer: 'CORQON turns operational signals into a weekly brief with clear actions. It helps reduce rework, instability, and hidden margin erosion.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-i-do-not-get-it',
    question: 'i do not get it',
    answer: 'No worries. Tell me what part is unclear: what we measure, how the weekly brief works, or why it matters for margins?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-i-am-confused',
    question: 'i am confused',
    answer: 'That is fair. Are you trying to understand signals, outputs, or rollout? Pick one and I will explain in plain terms.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-explain-like-i-am-five',
    question: 'explain like i am five',
    answer: 'CORQON helps leaders see where work gets messy and slow, then suggests what to fix each week. It focuses on team patterns, not individuals.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-can-you-be-more-specific',
    question: 'can you be more specific',
    answer: 'Yes. What is your context: number of teams, how often plans change, and where you see rework?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-what-do-you-need-from-us',
    question: 'what do you need from us',
    answer: 'Typically we need agreement on scope, team structure for aggregation, and access to a minimal set of operational signals. Want the minimal pilot checklist?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-is-this-for-startups-or-enterprise',
    question: 'is this for startups or enterprise',
    answer: 'CORQON fits fast growing companies and enterprise teams that need decision clarity. What size and structure are you working with?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-how-much-does-it-cost',
    question: 'how much does it cost',
    answer: 'Pricing depends on scope, team count, and integration needs. If you share your rough scope, I can explain what drives cost and what a pilot usually includes.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-do-you-have-pricing',
    question: 'do you have pricing',
    answer: 'Pricing is scope based. Most teams start with a pilot to validate signal quality and workflow fit. Want to define a pilot scope?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-can-you-show-an-example',
    question: 'can you show an example',
    answer: 'Yes. The weekly briefing section is the best sample. Do you want an example focused on volatility, fragmentation, or recovery signals?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-what-is-the-weekly-briefing',
    question: 'what is the weekly briefing',
    answer: 'It is a weekly narrative of what changed, why it matters, and what to do next. It includes a Monday plan with owners and expected outcomes.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-what-is-the-monday-plan',
    question: 'what is the monday plan',
    answer: 'A short list of prioritized actions for leadership and HR. Each action includes owner, effort, and intended outcome.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-what-does-privacy-safe-mean',
    question: 'what does privacy safe mean',
    answer: 'It means the product is designed for team and system level insights and avoids individual scoring. Governance and aggregation thresholds matter too.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-do-you-track-employees',
    question: 'do you track employees',
    answer: 'No. CORQON is built to avoid individual scoring and focus on system patterns leadership can act on.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-is-my-data-safe',
    question: 'is my data safe',
    answer: 'We support procurement friendly documentation and privacy aligned implementation. If you have specific requirements, we can review them in a pilot or via info@corqon.com.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-can-i-trust-this',
    question: 'can i trust this',
    answer: 'Trust comes from clear governance, transparent signals, and consistent measurement over time. If you tell me what you need to trust it, I can address that directly.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-this-feels-salesy',
    question: 'this feels salesy',
    answer: 'Understood. We try to keep it practical: signals, actions, outcomes. What would you like to evaluate based on evidence, not claims?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-this-is-not-useful',
    question: 'this is not useful',
    answer: 'Thanks for being direct. What would make it useful: clearer outcomes, implementation steps, or a sample week that matches your situation?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-you-are-not-answering',
    question: 'you are not answering',
    answer: 'Sorry about that. Ask again in one sentence and I will answer directly.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-i-do-not-like-this',
    question: 'i do not like this',
    answer: 'That is fair. Tell me what feels off and I will adjust. Are you looking for more detail, less jargon, or a clearer next step?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-can-you-speak-dutch',
    question: 'can you speak dutch',
    answer: 'I can, but the site is in English by default. If you prefer Dutch, tell me and I will respond in Dutch.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-where-are-you-located',
    question: 'where are you located',
    answer: 'CORQON works with companies across regions. For procurement, the key topics are data handling and governance. What region requirements do you have?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-i-want-to-explore-the-product',
    question: 'i want to explore the product',
    answer: 'The quickest path is to review the weekly briefing sample and the data streams section. Do you want a tour or a specific topic?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-i-want-to-understand-the-dashboard',
    question: 'i want to understand the dashboard',
    answer: 'The dashboard highlights system signals and weekly actions. Which area matters most: volatility, fragmentation, or risk trends?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-can-you-recommend-next-steps',
    question: 'can you recommend next steps',
    answer: 'Yes. First define the pilot scope, then connect minimum signals, establish a baseline, and run weekly actions. Want help drafting a pilot scope?',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-what-should-we-do-next',
    question: 'what should we do next',
    answer: 'The fastest next step is a walkthrough to confirm scope and feasibility. If you tell me team count and your stack, I can suggest what to bring.',
    tags: ['smalltalk'],
  },
  {
    id: 'smalltalk-can-you-point-me-to-the-right-place',
    question: 'can you point me to the right place',
    answer: 'Yes. Are you looking for data streams, the weekly briefing, privacy, or booking a pilot?',
    tags: ['smalltalk'],
  },
];
